version: 2
jobs:
  build:
    docker:
      - image: circleci/node:16.13

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            npm i -g aws-cdk
            npm i

      - run: cdk deploy
